### ISSUE TITLE
Application crashing at startup phase without internet connection 

### ISSUE THREAD

**Issue by piorosoii** [TRvACC/Ankara-Online#3]

**Comment by cptalpdeniz** [comment]
Is this due to no internet connection or the data type returned from `rasat.trvacc.net/metar/` is incorrect?

**Comment by cptalpdeniz** [comment]
For better handling, added connection checker will should fix the first issue mentioned in the previous reply. 
https://github.com/TRvACC/Ankara-Online/commit/9bb6847384205e4d6f1d71930163758da0dfd452

**Comment by piorosoii** [comment]
Not sure but 90% due to no internet connection

**Comment by cptalpdeniz** [comment]
Please test it and update this issue. ThanksOn Jul 16, 2023, at 12:18 AM, Can Bartu Topçuoğlu ***@***.***> wrote:﻿
Not sure but 90% due to no internet connection

**Comment by piorosoii** [comment]
It's caused by no internet connection already fixed by your commit (https://github.com/TRvACC/Ankara-Online/commit/9bb6847384205e4d6f1d71930163758da0dfd452) closing the issue. Thnaks for fixing.
